name: Build, Push & Deploy Flask App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker Image
      run: docker build -t flask-cicd-demo .

    # 🚀 Deployment to EC2
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop flask-cicd-demo || true
          docker rm flask-cicd-demo || true
          docker rmi flask-cicd-demo || true
          cd ~/flask-cicd-demo
          rm -rf *
          echo "${{ github.event.head_commit.message }}" > deploy.log
          # We'll use SCP later to send files if needed
